export const projects = [
  { 
    id: 'portfolio-01', 
    type:'Web Site',
    category: 'UI Development', 
    categorykr:'퍼블리싱',
    date:'2025',
    title: 'YK Corporate Business Center', 
    titlekr:'법무법인 YK 기업총괄센터',
    thumb: '/src/assets/images/main/img_work_yk.png',
    img:'/src/assets/images/work/img_yk.png',
    subimg:[
      '/src/assets/images/work/img_yk01.png',
      '/src/assets/images/work/img_yk02.png',
      '/src/assets/images/work/img_yk03.png'
    ],
    desc: '법무법인 YK 기업총괄센터 웹사이트 구축에 참여하여, 전체 페이지의 반응형 퍼블리싱 및 UI 구현을 담당하였습니다.\n또한 고객사와 직접 소통하며 요구사항을 반영하였고,\n피드백을 바탕으로 서브페이지 전반을 제작 및 개선하여 사용자 경험 향상에 기여하였습니다.',
    stack: ['html', 'CSS', 'js'],
    role:['Publishing : 50%'],
    view:'https://ykcbc.com/'
  },
  { 
    id: 'portfolio-02', 
    type:'Web Site',
    category: 'UI Development', 
    categorykr:'퍼블리싱',
    date:'2026',
    title: 'NOS GLOBAL', 
    titlekr:'노스글로벌',
    thumb: '/src/assets/images/main/img_work_nos.png',
    img:'/src/assets/images/work/img_nos.png',
    subimg:[
      '/src/assets/images/work/img_nos01.png',
      '/src/assets/images/work/img_nos02.png',
      '/src/assets/images/work/img_nos03.png'
    ],
    desc: '웹에이전시 노스글로벌 재직 당시, 자사 공식 홈페이지 구축을 담당하였습니다.\n전체 페이지 퍼블리싱을 포함하여 반응형 레이아웃 설계 및 UI 구현을 진행하였으며, \nGSAP을 활용한 인터랙션과 Three.js 기반의 3D/영상 효과를 적용해 브랜드 아이덴티티를 시각적으로 강화한 웹사이트를 제작했습니다.\n\ 디자인 시안을 기반으로 사용자 흐름을 고려한 모션을 설계하고,\n완성도 높은 인터랙티브 경험을 구현하는 데 집중했습니다.',
    stack: ['html', 'CSS', 'js', 'gasp','Three'],
    role:['Publishing : 100%'],
    view:'https://n-os.com/'
  },
  { 
    id: 'portfolio-03', 
    type:'Web Site',
    category: 'UI Development', 
    categorykr:'퍼블리싱',
    date:'2026',
    title: 'ELC Co., Ltd.', 
    titlekr:'ELC 주식회사',
    thumb: '/src/assets/images/main/img_work_elc.png',
    img:'/src/assets/images/work/img_elc.png',
    subimg:[
      '/src/assets/images/work/img_elc01.png',
      '/src/assets/images/work/img_elc02.png',
      '/src/assets/images/work/img_elc03.png'
    ],
    desc: '초정밀 유량계 및 반도체 부품 전문 기업인 elc 주식회사 웹사이트 구축에 참여하여, 전체 퍼블리싱 및 반응형 UI 구현을 담당하였습니다. 디자인 시안을 기반으로 다양한 디바이스 환경에 최적화된 반응형 레이아웃을 구현하고, 사용자 접근성과 가독성을 고려한 구조로 페이지를 구성했습니다. 또한 Dart의 API 연동을 통해 게시판 데이터를  출력하는 기능을 구현했습니다.',
    stack: ['html', 'CSS', 'js'],
    role:['Publishing : 100%'],
    view:'http://elck.nosboard.kr/'
  },
  { 
    id: 'portfolio-04', 
    type:'Web Site',
    category: 'UI Development', 
    categorykr:'퍼블리싱',
    date:'2026',
    title: 'suhwoo Technology', 
    titlekr:'서우 테크놀로지',
    thumb: '/src/assets/images/main/img_work_suhwoo.png',
    img:'/src/assets/images/work/img_suhwoo.png',
    subimg:[
      '/src/assets/images/work/img_suhwoo01.png',
      '/src/assets/images/work/img_suhwoo02.png',
      '/src/assets/images/work/img_suhwoo03.png'
    ],
    desc: '반도체 금형 전문 기업 웹사이트 구축에 참여하여, 전체 퍼블리싱 및 반응형 UI 구현을 담당하였습니다.\n디자인 시안을 기반으로 마크업 및 스타일링을 진행하고,\n 다양한 디바이스 환경에 최적화된 반응형 퍼블리싱을 구현했습니다.\n크로스 브라우징을 고려하여 안정적인 UI를 구현하고, 디자인 의도를 정확하게 반영하는 데 집중했습니다.',
    stack: ['html', 'CSS', 'js'],
    role:['Publishing : 100%'],
    view:'http://suhwoo.nosboard.kr/'
  },
  { 
    id: 'portfolio-05', 
    type:'Web Site',
    category: 'UI Development', 
    categorykr:'퍼블리싱',
    date:'2023',
    title: 'Gangwon Job Information Network', 
    titlekr:'강원일자리정보망 강소기업체험홍보관',
    thumb: '/src/assets/images/work/img_work_gwjob.png',
    img:'/src/assets/images/work/img_gwjob.png',
    subimg:[
      '/src/assets/images/work/img_gwjob01.png',
      '/src/assets/images/work/img_gwjob02.png',
      '/src/assets/images/work/img_gwjob03.png'
    ],
    desc: '강원특별자치도 강소기업 홍보 플랫폼 웹사이트 퍼블리싱을 담당하며, 관리자 기반 데이터 출력 구조를 설계했습니다.\n 기업 정보 콘텐츠가 효율적으로 관리 및 노출될 수 있도록 마크업 구조를 구성하고,\n반응형 UI 구현을 통해 다양한 디바이스 환경에서도 일관된 사용자 경험을 제공했습니다.\n 단순 퍼블리싱을 넘어 운영 및 확장성을 고려한 구조 설계에 중점을 두고 작업했습니다.',
    stack: ['html', 'CSS', 'js'],
    role:['Publishing : 100%'],
    git:'https://aldo814.github.io/gwjobNew/protoNew/',
    view:'https://job.gwd.go.kr/gwjob/empmn/desEntCntnts'
  },
  { 
    id: 'portfolio-06', 
    type:'Web Site',
    category: 'UI Development', 
    categorykr:'퍼블리싱',
    date:'2023',
    title: 'LearningHUB admin', 
    titlekr:'인키움 러닝허브 관리자',
    thumb: '/src/assets/images/work/img_work_hubAdmin.png',
    img:'/src/assets/images/work/img_hubAdmin.png',
    subimg:[
      '/src/assets/images/work/img_hubAdmin01.png',
      '/src/assets/images/work/img_hubAdmin02.png',
      '/src/assets/images/work/img_hubAdmin03.png',
      '/src/assets/images/work/img_hubAdmin04.png'
    ],
    desc: '인키움 러닝허브 관리자 페이지 퍼블리싱을 담당하여, 개발 연동을 고려한 마크업 구조를 구축하였습니다.\n버튼, 폰트, 테이블 등 공통 UI 요소에 대한 스타일을 정의하여 일관된 디자인 가이드를 수립하고,\n개발자가 효율적으로 활용할 수 있도록 정리된 형태로 페이지를 구현했습니다.\n또한 Sortable 라이브러리를 활용해 드래그 앤 드롭 기반의 트리 메뉴 기능을 구현하여,\n관리자가 직관적으로 메뉴 구조를 편집할 수 있도록 제작했습니다.',
    stack: ['html', 'CSS', 'js'],
    role:['Publishing : 100%'],
    git:'https://github.com/aldo814/LearningHUB_admin',
  },
  { 
    id: 'portfolio-07', 
    type:'Web Site',
    category: 'UI Development', 
    categorykr:'퍼블리싱',
    date:'2022',
    title: 'Smart Greencity', 
    titlekr:'강원생태평화지역 스마트그린도시',
    thumb: '/src/assets/images/work/img_work_green.png',
    img:'/src/assets/images/work/img_green.png',
    subimg:[
      '/src/assets/images/work/img_green01.png',
      '/src/assets/images/work/img_green02.png',
      '/src/assets/images/work/img_green03.png',
    ],
    desc: '강원도 생태평화지역 온라인 교육 및 취업지원 플랫폼의 다수 페이지(온라인 교육과정, 직업선호도/NCS 진단, 자기소개서 컨설팅, 취업진로상담 등)를 퍼블리싱하며,\n 사용자 흐름을 고려한 일관된 UI 구조와 반응형 화면을 구현하고 다양한 학습 및 진단 서비스 화면을 통합적으로 작업했습니다.',
    stack: ['html', 'CSS', 'js'],
    role:['Publishing : 30%'],
    git:'https://github.com/aldo814/greencity',
    view:'https://www.gwsgc.kr/portal/online_education'
  },
  { 
    id: 'portfolio-08', 
    type:'Web Site',
    category: 'UI Development', 
    categorykr:'퍼블리싱',
    date:'2021',
    title: 'Gangwon Employment Information Network', 
    titlekr:'강원일자리정보망',
    thumb: '/src/assets/images/work/img_work_gwjob_info.png',
    img:'/src/assets/images/work/img_gwjob_info.png',
    subimg:[
      '/src/assets/images/work/img_gwjob_info01.png',
      '/src/assets/images/work/img_gwjob_info02.png',
      '/src/assets/images/work/img_gwjob_info03.png',
    ],
    desc: '강원일자리정보망 리뉴얼 프로젝트에서 자기소개서, AI 면접, 온라인 채용박람회, 각종 진단 서비스 및 이러닝 학습, 마이페이지 등 약 80여 개 이상의 화면을 퍼블리싱하며, 서비스 전반의 UI/UX를 일관성 있게 개선하고 반응형 구조로 구현했습니다.',
    stack: ['html', 'CSS', 'js'],
    role:['Publishing : 30%'],
    git:'https://github.com/aldo814/gw-job',
    view:'https://job.gwd.go.kr/gwjob/empymn_sprt/coverletter_consulting'
  },
  { 
    id: 'portfolio-09', 
    type:'Web Site',
    category: 'UI Development', 
    categorykr:'퍼블리싱',
    date:'2021',
    title: 'Gyeonggi Council Website', 
    titlekr:'경기도의회 통합 웹사이트 구축',
    thumb: '/src/assets/images/work/img_work_ggc.png',
    img:'/src/assets/images/work/img_ggc.png',
    subimg:[
      '/src/assets/images/work/img_ggc01.png',
      '/src/assets/images/work/img_ggc02.png',
      '/src/assets/images/work/img_ggc03.png',
    ],
    desc: '경기도의회 대표 홈페이지를 포함한 기자실, 지역상담소, 의안, 어린이의회, 영문 사이트 등 다수의 서브 사이트 퍼블리싱을 수행하였습니다.\n 각 사이트 간 일관된 사용자 경험을 유지하도록 구현하고,\n다양한 콘텐츠 구조에 대응할 수 있는 반응형 퍼블리싱을 통해 안정적인 화면을 구축했습니다.',
    stack: ['html', 'CSS', 'js'],
    role:['Publishing : 100%'],
    git:'https://github.com/aldo814/gyeonggi-assembly',
    view:'https://www.ggc.go.kr/',
    links: [
      { name: '경기도 의회', url: 'https://www.ggc.go.kr/site/main/home' },
      { name: '경기도 의회 기자실', url: 'https://www.ggc.go.kr/site/proom/home' },
      { name: '경기도 의회 지역상담소', url: 'https://www.ggc.go.kr/site/regional/home' },
      { name: '경기도 의회 의안', url: 'https://www.ggc.go.kr/site/agendaif/home' },
      { name: '경기도 어린이 의회', url: 'https://www.ggc.go.kr/site/children/home' },
      { name: '경기도 의회 영문', url: 'https://www.ggc.go.kr/site/global/home' }
    ]
  },
  { 
    id: 'portfolio-10', 
    type:'Web Site',
    category: 'UI Development', 
    categorykr:'퍼블리싱',
    date:'2021',
    title: 'Gwangyang FEZ Portal', 
    titlekr:'광양만권경제자유구역청',
    thumb: '/src/assets/images/work/img_work_grez.png',
    img:'/src/assets/images/work/img_grez.png',
    subimg:[
      '/src/assets/images/work/img_grez01.png',
      '/src/assets/images/work/img_grez02.png',
      '/src/assets/images/work/img_grez03.png',
    ],
    desc: '광양만권경제자유구역청 행정포털 시스템 퍼블리싱을 담당하여, 메인 및 서브 페이지를 구축하였습니다.\nIE8 환경을 기준으로 크로스 브라우징을 고려해 구현하였으며,\n웹 접근성과 웹표준을 준수하여 안정적인 UI를 제작했습니다.\n또한 메인 화면에 드래그 기반 인터랙션을 적용하여 사용자 편의성을 향상시켰습니다.',
    stack: ['html', 'CSS', 'js'],
    role:['Publishing : 100%'],
    git:'https://aldo814.github.io/grez/',
  },
  { 
    id: 'portfolio-11', 
    type:'Web Site',
    category: 'UI Development', 
    categorykr:'퍼블리싱',
    date:'2021',
    title: 'LOTTE CLOUD`s Landing', 
    titlekr:'롯데이노베이트 랜딩페이지',
    thumb: '/src/assets/images/work/img_work_lt_landing.png',
    img:'/src/assets/images/work/img_lt_landing.png',
    subimg:[
      '/src/assets/images/work/img_lt_landing01.png',
      '/src/assets/images/work/img_lt_landing02.png',
      '/src/assets/images/work/img_lt_landing03.png',
    ],
    desc: '롯데이노베이트(구 롯데클라우드)를 소개하는 랜딩페이지를 제작하였으며, PC와 Mobile 환경에 최적화된 반응형 퍼블리싱을 진행했습니다. 브랜드 아이덴티티를 살린 깔끔한 UI와 함께 사용자 흐름을 고려한 레이아웃 설계를 통해 정보 전달력을 높였고, 다양한 디바이스에서도 일관된 경험을 제공하도록 구현했습니다. 또한 인터랙션 요소를 적절히 활용해 사용자 몰입도를 높였으며, 완성도 높은 결과물로 클라이언트 측에서도 긍정적인 피드백을 받았습니다.',
    stack: ['html', 'CSS', 'js'],
    role:['Publishing : 100%'],
    view:'https://dtoncloud.com/',
  },
  { 
    id: 'portfolio-12', 
    type:'Web Site',
    category: 'UI Development', 
    categorykr:'퍼블리싱',
    date:'2019',
    title: 'LOTTE CLOUD`s Dashboard', 
    titlekr:'롯데클라우드 대시보드',
    thumb: '/src/assets/images/work/img_work_lt.png',
    img:'/src/assets/images/work/img_lt.png',
    subimg:[
      '/src/assets/images/work/img_lt01.png',
      '/src/assets/images/work/img_lt02.png',
      '/src/assets/images/work/img_lt03.png',
    ],
    desc: '롯데이노베이트(구 롯데정보통신)에서 구축한 롯데클라우드 대시보드 퍼블리싱에 참여하여, 데이터 시각화를 중심으로 한 UI 구현을 담당했습니다. 다양한 차트와 그래프 컴포넌트를 활용해 복잡한 데이터를 직관적으로 전달할 수 있도록 구성하였으며, 사용자 편의성을 고려한 레이아웃과 인터랙션을 설계해 대시보드의 가독성과 활용도를 높였습니다. 또한 일관된 디자인 시스템을 기반으로 안정적인 화면을 구현했으며, 완성도 높은 결과물로 클라이언트로부터 긍정적인 평가를 받았습니다.',
    stack: ['html', 'CSS', 'js'],
    role:['Publishing : 100%'],
  },
  { 
    id: 'portfolio-13', 
    type:'Web Site',
    category: 'UI Development', 
    categorykr:'퍼블리싱',
    date:'2019',
    title: 'SUWON UNIVERSITY', 
    titlekr:'수원대학교',
    thumb: '/src/assets/images/work/img_work_suwon.png',
    img:'/src/assets/images/work/img_suwon.png',
    subimg:[
      '/src/assets/images/work/img_suwon01.png',
      '/src/assets/images/work/img_suwon02.png',
      '/src/assets/images/work/img_suwon03.png',
    ],
    desc: '수원대학교 웹사이트 리뉴얼 프로젝트 퍼블리싱을 담당하였으며, 웹접근성과 웹표준을 준수하여 관련 인증 마크를 획득한 프로젝트입니다. CMS인 ZCMS를 기반으로 작업하여 관리자 운영 환경을 고려한 구조로 구현하였고, 다양한 사용자 환경에서도 안정적으로 동작할 수 있도록 반응형 UI와 시맨틱 마크업을 적용했습니다. 또한 접근성을 고려한 콘텐츠 구조와 인터랙션을 설계해 사용자 편의성과 가독성을 높이는 데 중점을 두었습니다.',
    stack: ['html', 'CSS', 'js'],
    role:['Publishing : 30%'],
    view:'https://www.suwon.ac.kr/'
  },
  
  { 
    id: 'portfolio-14', 
    type:'Web Site',
    category: 'design', 
    categorykr:'디자인',
    date:'2019',
    title: 'Enkiwi', 
    titlekr:'엔키위 웹사이트 제안 시안',
    thumb: '/src/assets/images/work/img_work_enkiwi.png',
    img:'/src/assets/images/work/img_enkiwi.png',
    subimg:[
      '/src/assets/images/work/img_enkiwi01.png',
    ],
    desc: '엔키위 제안용 시안입니다.엔키위는 네이버 클라우드 통합관리 서비스 전문기업입니다.\nCI의 컬러와 이미지를 활용하여 작업하였습니다',
    stack: ['photoshop'],
    role:['design : 100%'],
  },
  { 
    id: 'portfolio-15', 
    type:'Web Site',
    category: 'design', 
    categorykr:'디자인',
    date:'2019',
    title: 'PDSOFT BUSNESS CARD', 
    titlekr:'피디소프트 명함디자인',
    thumb: '/src/assets/images/work/img_work_pdcard.png',
    img:'/src/assets/images/work/img_pdcard.png',
    subimg:[
      '/src/assets/images/work/img_pdcard01.png',
    ],
    desc: 'PDSOFT 명함 디자인 작업입니다.해외 사업을 병행하는 기업 특성을 고려하여, 앞면은 한글, 뒷면은 영문으로 구분해 제작하였습니다.\n불필요한 요소를 최소화한 심플한 레이아웃을 적용하고, CI 컬러와 요소를 활용하여 브랜드 정체성을 효과적으로 전달하고자 하였습니다.',
    stack: ['Illustrator'],
    role:['design : 100%'],
  },
  
];